# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: SpiritLHL's Python blog
description: Personally explore Python's study notes.
github_username: spiritLHL
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "jupyter_notebook_blogs"

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
url: "https://spiritLHL.github.io" # the base hostname & protocol for your site, e.g. http://example.com

###########################################################
#########  Special Instructions for baseurl ###############
#
#### Scenario One: If you do not have a Custom Domain #####
#    -  if you are not using a custom domain, the baseurl *must* be set to your repo name
# 
####  Scenario Two: If you have a Custom Domain #####
# 1. If your domain does NOT have a subpath, this leave this value as ""
# 2. If your domain does have a subpath, you must preceed the value with a / and NOT have a / at the end.  
#      For example: 
#           "" is valid
#           "/blog"        is valid
#            "/blog/site/" is invalid  ( / at the end)
#            "/blog/site"  is valid
#            "blog/site"   is invalid  ( because doesn't begin with a /)
#
# 3. You must replace the parameter `baseurl` in _action_files/settings.ini with the same value as you set here but WITHOUT QUOTES.
#
baseurl: "/jupyter_notebook_blogs" # the subpath of your site, e.g. "/blog".

# Github和Twitter是可选的：
minima:
  social_links:
    twitter: Dan.ajax
    github: spiritLHL

# 将此设置为true可获得LaTeX数学方程式支持
use_math: true

# 将此属性设置为true可以在首页上的标题下显示博客文章的摘要。
show_description: true

# 将其设置为true以在主页上显示图像预览（如果存在）
show_image: true

# 将此属性设置为true可使用hypothes.is（https://web.hypothes.is/）打开注释
annotations: true

# 将此设置为true可在每个帖子上显示标签
show_tags: true

# 如果您有要使用的Google Analytics（分析）ID，请在此处添加
google_analytics: G-3TD0N5Q1SC

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# 此设置使您可以将页面整理在_pages文件夹中
include:
  - _pages

# 这指定默认情况下为笔记本帖子打开的徽章。
default_badges:
  github: true
  binder: true
  colab: true

# 在帖子描述中转义HTML
html_escape:
  description: false

# 下面的所有内容均应保留。修改可能会中断快速页面
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# See https://jekyllrb.com/docs/pagination/
# 为了使分页生效，您不能在存储库的根目录下拥有index.md，而必须将此文件重命名为index.html
paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# 限制xml的大小，因为它可能会变得很大。
feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true
 
 #添加sitemap
 url: "https://spiritlhl.github.io/jupyter_notebook_blogs/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
